#!/bin/bash

# Function to update the weight value
update_weight() {
    local file="$1"
    local line_number="$2"
    local new_weight="$3"
    local current_weight="$4"
    sed -i -e "${line_number}s/${current_weight}/${new_weight}/1" "$file"
}

# Specify the file path and the target string to look for
# file_path="/Users/nbc404/Documents/sourcecode/test3/grid.tf"
# target_string="dev.example.com"
# new_weight=96
    local file="$1"
    local target_string="$2"
    local new_weight="$3"
# Search for the target string and its associated weight
while IFS= read -r line; do
    if [[ "$line" == *"$target_string"* ]]; then
        # If the target string is found, find the weight in the previous lines
        line_number=$(grep -n "$target_string" "$file_path" | cut -d: -f1)
        #echo $line_number
        while [ "$line_number" -gt 1 ]; do
            line_number=$((line_number - 1))
            previous_line=$(sed -n "${line_number}p" "$file_path")
            if [[ "$previous_line" == *weight* ]]; then
                echo $previous_line
                echo $line_number
                # Extract the current weight value
                current_weight=$(echo "$previous_line" | grep -o '[[:digit:]]*')

                # Update the weight value (replace 'new_weight' with the desired value)
                update_weight "$file_path" "$line_number" "$new_weight" $current_weight

                echo "Weight updated from $current_weight to $new_weight."
                break
            fi
        done
    fi
done < "$file_path"
